### ISSUE TITLE
AudioVisualizer

### ISSUE THREAD

**Issue by hyperxmason** [SlimeNull/AudioVisualizer#1]
I ran the exe and nothing happens but a straight line is this how it's supposed to be?
![Untitled](https://user-images.githubusercontent.com/74578563/236987028-682256dc-a8c8-4941-be80-8df846f8c714.png)

**Comment by SlimeNull** [comment]
可能是没有正确识别音频设备. 程序使用的 WasapiCapture 做的音频捕捉, 你可以看看是否是这方面的问题.

**Comment by SlimeNull** [comment]
It may be that the audio device is not properly identified. The program uses WasapiCapture to do audio capture, you can see if this is the problem.

--- 
可能是没有正确识别音频设备. 程序使用的 WasapiCapture 做的音频捕捉, 你可以看看是否是这方面的问题.

**Comment by SlimeNull** [comment]
It is recommended to use the DirectX version, and I will change the repository frequently, so it is possible that the direct build run may not work. You can take a look at the code first.

---
建议使用 DirectX 版本, 并且这仓库会经常被我改动, 所以直接 build 运行也确实可能出现没效果的现象. 你可以看看代码先.
